#!/bin/sh

# 15min (60*15=900)
MAX_TIME=900

LOGDIR=`date '+%Y%m%d-%H%M%S'`
mkdir -p $LOGDIR

. ./test_cond

function do_sysbench ()
{
	sysbench \
	  --db-driver=mysql \
	  --mysql-host=$DBHOST \
	  --mysql-db=$DBNAME \
	  --mysql-user=$DBUSER \
	  --mysql-password=$DBPASS \
	  --threads=$1 \
	  --time=$2 \
	  --tables=$NUM_TABLES \
	  --table_size=$TABLE_SIZE \
	  --report-interval=1 \
	  oltp_read_write \
	  run
}

for threads in 1 2 4 8 16 32 64 128 256; do
	LOGFILE=$(printf log-%03d.txt $threads)
	do_sysbench $threads $MAX_TIME | tee $LOGDIR/$LOGFILE
done

