#!/bin/sh

# 15min (60*15=900)
MAX_TIME=900

LOGDIR=`date '+%Y%m%d-%H%M%S'`
mkdir -p $LOGDIR

. ./test_cond

function do_sysbench ()
{
	sysbench \
	  --test=/usr/local/share/sysbench/oltp.lua \
	  --db-driver=mysql \
	  --mysql-host=$DBHOST \
	  --mysql-db=$DBNAME \
	  --mysql-user=$DBUSER \
	  --mysql-password=$DBPASS \
	  --num-threads=$1 \
	  --max-time=$2 \
	  --max-requests=0 \
	  --oltp-tables-count=$NUM_TABLES \
	  --oltp-table-size=$TABLE_SIZE \
	  --oltp-test-mode=complex \
	  run
}

for threads in 1 2 4 8 16 32 64 128 256; do
	LOGFILE=$(printf log-%03d.txt $threads)
	do_sysbench $threads $MAX_TIME | tee $LOGDIR/$LOGFILE
done

